### ISSUE TITLE
Only hub members can create PORs

### ISSUE THREAD

**Issue by shawnlauzon** [shawnlauzon/joatu#19]
Hub members can only fully interact with their hub (send messages, add comments, create projects, etc.) On all other hubs, they have the same permissions as users that aren't signed in at all.

**Comment by shawnlauzon** [comment]
Issue #10 says that new users are auto-assigned to a hub based on their location, so no, members cannot exist without a hub. Should that be changed?

I think I don't understand your 2nd point. If I understand correctly, the first X members could never join the platform.

**Comment by joatu** [comment]
What happens if a user attempts to sign up but there is no hub in their vicinity?

My second point was about allowing people to sign up, fill out a profile, create offers/requests, but not be able to see anybody else's POR until the appropriate number of members have joined+they have a hub. There was a website I used to go on that 'opened' for a city once it reached a minimum threshold of members, I really appreciated it because it incentivized the first members to go and recruit more if they wanted to make use of the platform.

**Comment by shawnlauzon** [comment]
Good questions and suggestion!

I copied your question about no hub in vicinity to #10 and created #35 for the second.

This issue is about limiting the ability to create projects to hub members.
